#!/bin/bash -

DEEPORNOT="-maxdepth 1" #시작 경로 자체만 검색한다.

#옵션 인수 처리하기:
while getopts 'c:irR' opt; 
do
        case "${opt}" in 
            c)      #찾은 파일들을 지정된 dir에 복사
                COPY=YES
                DESTDIR="$OPTARG" #-c다음에 그 옵션의 값을 
                ;;
            i)      #검색시 대소문자를 가리지 않을 것
                CASEMATCH='-i'
                ;;
            [Rr]) #하위 디렉토리들도 재귀적으로 검색할 것
                unset DEEPORNOT #최대 깊이 변수를 해제시켜 하위디렉토리를 재귀적으로 탐색해나가도록 함.
                ;;
            *) 
                exit 2 #설정한 값 그 외 잡 옵션은 해당 섹션으로 넘어옴 (else같은거)
                ;;
    esac
done
shift $((OPTIND - 1))

PATTERN=${1:-PDF document}

STARTDIR=${2:-.}
find $STARTDIR $DEEPORNOT -type f | while read FN
do
    file $FN | egrep -q $CASEMATCH "$PATTERN"
    if (( $? == 0 )) #찾음
    then 
            echo $FN
            if [[ $COPY ]]
            then
                cp -p $FN $DESTDIR
            fi
    fi
done